//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrashPickUp
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterdUserInfo
    {
        public int ID { get; set; }
        public string PickupDay { get; set; }
        public double MonthlyBill { get; set; }
        public string currentUser_Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
